project:
  type: website

website:

  title: "Tips and tricks"
  site-url: https://frbcesab.github.io/tips-and-tricks
  description: "Tips and tricks"
  
  favicon: images/favicon.png
  
  navbar:
  
    logo: "images/favicon.png"
    
    right:
      - text: "Posts"
        href: index.qmd
      - contribute.qmd
      - about.qmd
      - icon: github
        href: https://github.com/frbcesab/tips-and-tricks
      - icon: rss
        href: index.xml
        
  page-footer: 
  
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/frbcesab/tips-and-tricks/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true
    
  comments: 
    utterances:
      repo: frbcesab/tips-and-tricks
      label: blog
      theme: github-light
      issue-term: pathname
      
format:
  html:
  
    theme: [litera,styles.scss]
    
    code-copy: true
    code-overflow: wrap
    code-line-numbers: true
    code-block-border-left: true
    highlight-style: nord
